---
title: "Dec_Tree"
author: "Eva Kleingeld"
date: "December 22, 2016"
output: html_document
---


First clear your working environment and install all necessary packages

```{r}
rm(list=ls())

# Install packages
#install.packages("caret")
#install.packages("caret", dependencies = c("Imports", "Depends", "Suggests"))



```

Now load in the test and train sets and split them into target and predictor sets

```{r}
# Load train
load("/usr/people/kleingel/Projects/MLProject/Train_BIG_noCat.Rda")

# Load test
load("/usr/people/kleingel/Projects/MLProject/Test_BIG_noCat.Rda")

# Split train set into target and predictors 
Target_Train <- Train_set$TRoad
Train_set <- subset(Train_set, select=-c(TRoad))

# Split test set into target and predictors
Target_Test <- Test_set$TRoad
Test_set <- subset(Test_set, select = -c(TRoad))

```

# Build a decision tree

```{r}
library(caret)
library(doParallel)
library(parallel)
library(rpart)
library(rattle)

cluster_1<-makeCluster(3)
registerDoParallel(cluster_1)
getDoParWorkers()

trainC <- trainControl(method = "cv", number = 3, allowParallel = TRUE)
system.time(
DecTree <- train(x  = Train_set, 
                     y = Target_Train, 
                     method = "rpart", 
                     trControl = trainC))

# Stop the cluster
stopCluster(cluster_1)
registerDoSEQ()

#Save the model
save(DecTree, file =  "/usr/people/kleingel/Projects/MLProject/DecTree.Rda")

```


# Analysis

```{r}
#Load the model
load("/usr/people/kleingel/Projects/MLProject/DecTree.Rda")


#Summary (If you plot this summary you will get a large amount of numbers printed to your screen, which won't be very interpretable. Therefore I commented this command.)
#summary(DecTree)

# Get the RMSE and R2 for each of the folds
DecTree$results

# Plot the decision tree
png("TreePlot_R2")
fancyRpartPlot(DecTree$finalModel)
dev.off()

# Variable importance
DecTree_Imp <- varImp(DecTree)

#Predict
DecTree_Predict <- extractPrediction(models = list(DecTree), testX = Test_set, testY = Target_Test)

# THIS PLOT IS TOO COMPUTATIONALLY INTENSIVE
# Plot observed versus predicted and save to a png
#png("DecTree_ObsPred")
#plotObsVsPred(DecTree_Predict)
#dev.off()

# Plot the same manually (ggplot2) 
png("DecTree_ObsPred")
ggplot() + geom_point(aes(x = DecTree_Predict$obs, y = DecTree_Predict$pred))
dev.off()


# Calculate the residuals for the train/test sets
DecTree_Residuals <- (DecTree_Predict$obs - DecTree_Predict$pred)

# Plot the residuals versus the observed values
png("DecTree_ResPlot")
plot(DecTree_Predict$obs,DecTree_Residuals, 
  ylab="Residuals", xlab="Observed road temperature", 
  main="Residual plot") 
abline(0, 0)                  
dev.off()





```















