---
title: "Neuralnet_R2"
author: "Eva Kleingeld"
date: "December 19, 2016"
output: html_document
---


First clear your working environment and install all necessary packages

```{r}
rm(list=ls())

# Install packages
#install.packages("caret")
#install.packages("caret", dependencies = c("Imports", "Depends", "Suggests"))



```

Now load in the test and train sets and split them into target and predictor sets

```{r}
library(caret)
# Load train
load("/usr/people/kleingel/Projects/MLProject/Train_3D_noPCA.Rda")

# Load test
load("/usr/people/kleingel/Projects/MLProject/Test_3D_noPCA.Rda")

# # Reduce the train set to 1% of its original size 
# # 1% equals..
# The_One_Percent <- createDataPartition(Train_set$TRoad, p = 0.01, list = FALSE)
# One_Percent_Train <- Train_set[The_One_Percent, ]
# 
# # Split into Train_set and Target_Train
# Target_Train <- One_Percent_Train$TRoad
# Train_set <- subset(One_Percent_Train, select=-c(TRoad))

# DOESN'T WORK. neuralnet somehow thinks you are doing classification if you center scale the target var.
# Test the effect of centering and scaling the target variable 
#xTrans <- preProcess(as.data.frame(Target_Train), method = c("center", "scale"), na.remove = TRUE)
#Target_Train <- as.vector(predict(xTrans, as.data.frame(Target_Train)))


# Split train set into target and predictors
Target_Train <- Train_set$TRoad
Train_set <- subset(Train_set, select=-c(TRoad))

# Split test set into target and predictors
Target_Test <- Test_set$TRoad
Test_set <- subset(Test_set, select = -c(TRoad))


# Remove all the predictors which don't say much about TW
Train_set <- Train_set[, 1:7]

Test_set <- Test_set[, 1:7]


# Remove TD, which is highly correlated with TL
cor(Train_set$TL, Train_set$TD)
Train_set <- subset(Train_set, select=-c(TD))

cor(Test_set$TL, Test_set$TD)
Test_set <- subset(Test_set, select=-c(TD))

```

# Build a neural network with neuralnet

Here I build a neural network with the neuralnet package and caret 

```{r}
library(caret)
library(doParallel)
library(parallel)
library(neuralnet)
library(doMC)

#cluster_1<-makeCluster(3)
#registerDoParallel(cluster_1)

registerDoMC(cores = 4)
getDoParWorkers()

NN_trainC <- trainControl(method = "cv", number = 10, allowParallel = TRUE, returnData = FALSE)

NeuralNetw <- train(x  = Train_set, 
                     y = Target_Train, 
                     method = "neuralnet", 
                     trControl = NN_trainC,
                     tuneLength = 3)
 
                    #  hidden = c(6),
                    #  trControl = NN_trainC,
                    # savePredictions = "none")
# , 
#                      linear.output = TRUE,
#                      lifesign = 'minimal', 
#                      trControl = NN_trainC
#                     )

stopCluster(cluster_1)
registerDoSEQ()


summary(NeuralNetw)

print(NeuralNetw$results)



# Test if any NA

for(i in seq_along(colnames(Train_set))){
  print(i)
  print(any(is.na(Train_set[, i])))
  print(summary(Train_set[, i]))
}


any(is.na(Test_set))




``` 












